# Generated by Django 3.1.4 on 2020-12-28 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('mapurl', models.URLField(max_length=500)),
                ('img1', django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default.jpg', force_format='JPEG', keep_meta=True, quality=75, size=[500, 500], upload_to='property/pics')),
                ('img2', django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default.jpg', force_format='JPEG', keep_meta=True, quality=75, size=[500, 500], upload_to='property/pics')),
                ('img3', django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default.jpg', force_format='JPEG', keep_meta=True, quality=75, size=[500, 500], upload_to='property/pics')),
                ('isactive', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='', max_length=200)),
                ('house', models.CharField(default='', max_length=200)),
                ('town', models.CharField(default='', max_length=200)),
                ('pincode', models.CharField(default='', max_length=12)),
                ('phone', models.CharField(default='', max_length=12)),
                ('isvendor', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='pslot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isfw', models.BooleanField(default=False)),
                ('istw', models.BooleanField(default=False)),
                ('isavailable', models.BooleanField(default=True)),
                ('isroofed', models.BooleanField(default=True)),
                ('isfenced', models.BooleanField(default=True)),
                ('propertyid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='property_vendor.property')),
            ],
        ),
    ]
