# Generated by Django 3.1.4 on 2020-12-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_vendor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='mapurl',
            field=models.CharField(default='', max_length=500),
        ),
    ]
