# Generated by Django 3.1.4 on 2021-01-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_vendor', '0002_auto_20201228_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='district',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='place',
            field=models.CharField(default='', max_length=200),
        ),
    ]
