# Generated by Django 3.1.4 on 2021-01-14 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property_vendor', '0003_auto_20210110_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('vtype', models.IntegerField(default=2)),
                ('regnum', models.CharField(default='', max_length=12)),
                ('status', models.BooleanField(default=True)),
                ('pslotid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='property_vendor.pslot')),
                ('userid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
