# Generated by Django 3.1.4 on 2021-01-16 05:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('property_vendor', '0004_bookingdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingdetails',
            old_name='date',
            new_name='bdate',
        ),
        migrations.AddField(
            model_name='bookingdetails',
            name='cdate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
