# Generated by Django 3.1.4 on 2021-01-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_vendor', '0006_auto_20210116_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='upi',
            field=models.CharField(blank=True, default=None, max_length=12, null=True),
        ),
    ]
