# Generated by Django 3.1.4 on 2021-01-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_vendor', '0007_property_upi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='upi',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
