# Generated by Django 3.1.4 on 2021-01-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_vendor', '0008_auto_20210117_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='pslot',
            name='rate',
            field=models.IntegerField(default=2),
        ),
    ]
