# Generated by Django 3.1.4 on 2021-01-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_vendor', '0009_pslot_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetails',
            name='amt',
            field=models.IntegerField(default=11),
            preserve_default=False,
        ),
    ]
