# Generated by Django 3.1.4 on 2021-01-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_vendor', '0010_bookingdetails_amt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetails',
            name='amt',
            field=models.IntegerField(default=0),
        ),
    ]
