# Generated by Django 3.1.4 on 2021-01-17 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property_vendor', '0011_auto_20210117_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='reviewDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(default='', max_length=200)),
                ('propertyid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='property_vendor.property')),
                ('userid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
