# Generated by Django 3.1.4 on 2021-04-09 05:16

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('property_vendor', '0012_reviewdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='img1',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=75, size=[500, 500], upload_to='property/pics'),
        ),
        migrations.AlterField(
            model_name='property',
            name='img2',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=75, size=[500, 500], upload_to='property/pics'),
        ),
        migrations.AlterField(
            model_name='property',
            name='img3',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=75, size=[500, 500], upload_to='property/pics'),
        ),
    ]
